### ISSUE TITLE
IndexError: string not matched

### ISSUE THREAD

**Issue by tleish** [tkadauke/i18n_tools#7]
Discovered an issue where one yaml language file was accidentally formatted in such a way that it invalidated another language yaml file.

`file: common.en.yml`

``` yaml
en:
  common:
    shopping:
      cart: 'Cart'
      ...
```

`file: new.en.yml`

``` yaml
en:
  common:
  shopping:
    checkout: 'Checkout'
    ...
```

Note that the 2nd yaml format is valid, but shopping key was not indented enough to make it valid.  This overwrote `en.common` values in the application to be invalid.

When using i18n_tools to check translations, an error was returned:

```
$ rake translations:missing
rake aborted!
IndexError: string not matched
/Users/tleishman/.rvm/gems/ruby-2.1.2/gems/i18n_tools-0.1.6/lib/i18n_tools/missing_scanner.rb:45:in `[]='
/Users/tleishman/.rvm/gems/ruby-2.1.2/gems/i18n_tools-0.1.6/lib/i18n_tools/missing_scanner.rb:45:in `block in results'
/Users/tleishman/.rvm/gems/ruby-2.1.2/gems/i18n_tools-0.1.6/lib/i18n_tools/missing_scanner.rb:16:in `each'
/Users/tleishman/.rvm/gems/ruby-2.1.2/gems/i18n_tools-0.1.6/lib/i18n_tools/missing_scanner.rb:16:in `results'
/Users/tleishman/.rvm/gems/ruby-2.1.2/gems/i18n_tools-0.1.6/tasks/i18n_tools.rake:26:in `block (2 levels) in <top (required)>'
```
